^HSI hangseng
9988.HK alibaba
0175.HK ji-li
NIO  wei-lei
BABA alibaba
3900.HK lv-cheng
0788.HK zhong-guo-tie-ta
1810.HK xiao-mi
1787.HK shan-dong-huang-jin
1093.HK shi-yao
2359.HK yao-ming-kang-de
1833.HK ping-an-hao-yi-sheng
1951.HK jin-xin-sheng-zhi
1060.HK ali-ying-ye
3690.HK mei-tuan
LK rui-xing-ka-fei
EDU xin-dong-fang
TAL hao-wei-lai
TSM tai-ji-dian
AAPL apple
AMT mei-guo-tie-ta
IQ ai-qi-yi
PDD pdd
BIDU baidu
HUYA hu-ya
0981.HK zhong-xin-guo-ji
TSLA te-si-la
BILI bi-li-bi-li
1211.HK bi-ya-di
9922.HK jiu-mao-jiu
3692.HK han-sen-zhi-yao
0700.HK teng-xun
