9988.HK alibaba
0175.HK 吉利
NIO  蔚来
BABA alibaba
3900.HK 绿城
0788.HK 中国铁塔
1810.HK 小米
1787.HK 山东黄金
1093.HK 石药
2359.HK 药明康德
1833.HK 平安好医生
1951.HK 锦欣生殖
1060.HK 阿里影业
3690.HK 美团
LK 瑞幸
EDU 新东方
TAL 好未来
TSM 台积电
AAPL 苹果
AMT 美国电塔
IQ 爱奇艺
PDD pdd
BIDU 百度
HUYA 虎牙
